/**
 * This file describes a generated frontend/<uuid>.json file that is generated by an app-kit build server
 */
import { FeatureBase } from "../Features";

export type UserContentImage = {
  imageUrl: {
    '1x': string,
    '2x': string,
    '4x'?: string,
    '8x'?: string,
  }
}

export type FilledUserContent = {
  images: Record<string, UserContentImage>,
  texts: Record<string, string>,
  configuration: Record<string, string>,
}

export type Frontend = FeatureBase & {
  userContent: FilledUserContent
}