/**
 * This file describes a generated glossary/<uuid>.json file that is generated by an app-kit build server
 */
import { FeatureBase } from "../Features";
import { ImageUrls } from "../Image";

export type GlossaryEntry = {
  definition: string,
  synonyms: string[],
  imageUrl: ImageUrls, 
}

export type Glossary = FeatureBase & {
  glossary: Record<string, GlossaryEntry>
}