/**
 * This file describes a generated glossary/<uuid>.json file that is generated by an app-kit build server
 */
import { DetailFeature } from "~/types/localcosmos/types/Features";

export type GlossaryDefinition = {
  definition: string,
  synonyms: string[]
  imageUrl?: string | null
}

export type Glossary = DetailFeature & {
  glossary: Record<string, GlossaryDefinition>
}