/**
 * This file describes a localcosmos/features/Map/{uuid}/{uuid}.json file that is generated by Local Cosmos App Kit
 */
import { FeatureBase } from '../Features';
import { Taxon } from 'BackboneTaxonomy';
import { GeoJSONFeatureCollection } from '../GeoJSON';

export type MapOptions = {
  initialZoom: number,
  initialLatitude: number,
  initialLongiture: number,
  includeObservationFormsAsFilters: boolean,
}

export enum MapTypes {
  observations = 'observations'
}

export type MapTaxonomicFilter = {
  name: string,
  taxa: Taxon[],
  position: number,
}

export type MapObservationFormFilter = {
  observationformId: number,
  observationFormUuid: string,
  name: string,
}

export type Map = FeatureBase & {
  options: MapOptions,
  mapType: MapTypes,
  geometries: {
    projectArea?: GeoJSONFeatureCollection,
  },
  taxonomicFilters: MapTaxonomicFilter[],
  observationFormfilters: MapObservationFormFilter[]
}