/**
 * This file describes the TaxonProfiles files generated by Local cosmos App Kit
 */

import { Taxon, LatnameSearchTaxon, VernacularSearchTaxon, TaxonScientificName } from './BackboneTaxonomy';
import { ImageUrls } from '../Image';
import { MatrixFilter } from './NatureGuide';
import { GenericFormReference } from './GenericForm';


export type VernacularNamesDict = Record<string,string>

export type TaxonImageSet = {
  taxonProfileImages: ImageUrls[],
  nodeImages: ImageUrls[],
  taxonImages: ImageUrls[],
}

export type TaxonProfileReference = Taxon & {
  vernacularNames: VernacularNamesDict,
  alternativeVernacularNames: VernacularNamesDict,
  images: TaxonImageSet

}

/**
 * localcosmos/features/TaxonProfiles/{uuid}/search.json
 */
export type TaxonProfilesSearchIndex = {
  taxonLatname: {
    [startLetter: string]: LatnameSearchTaxon[]
  },
  vernacular: {
    [locale: string]: {
      [startLetter: string]: VernacularSearchTaxon[]
    }
  }
}

/**
 * localcosmos/features/TaxonProfiles/{uuid}/registry.json
 */
export type TaxonProfilesRegistry = Record<string, TaxonProfileReference>

/**
 * localcosmos/features/TaxonProfiles/vernacular/{locale}.json
 */
export type TaxonProfileList = VernacularSearchTaxon[]



/**
 * The below describes the full Taxon Profile, stored in a separate file for each taxon
 * localcosmos/features/TaxonProfiles/{taxon_source}/{nameUuid}.json
 */


// old
export type TraitValue = {
  encodedSpace: string,
  imageUrl: string,
}

export type Trait = {
  matrixFilter: MatrixFilter,
  values: TraitValue[],
  hasMoreSpecificOccurrence: boolean,
}

export type TaxonText = {
  taxonTextType: string,
  shortText: string,
  shortTextKey: string,
  longText: string,
  longTextKey: string,
}

export type TaxonProfile = Taxon & {
  vernacular: {
    [locale: string]: string
  },
  allVernacularNames: {
    [locale: string]: string
  },
  nodeNames: string[],
  nodeDecisionRules: any, // todo: unknown
  traits: Trait[],
  texts: TaxonText[],
  images: TaxonImageSet,
  synonyms: TaxonScientificName[],
  gbifNubKey?: string,
  genericForms?: GenericFormReference[],
  templateContents?: object[],
  tags: string[],
}

export function taxonToReference(taxonProfile: TaxonProfile): Taxon | undefined {
  if (!taxonProfile) {
    return;
  }

  return {
    nameUuid: taxonProfile.nameUuid,
    taxonSource: taxonProfile.taxonSource,
    taxonLatname: taxonProfile.taxonLatname,
    taxonAuthor: taxonProfile.taxonAuthor,
    taxonNuid: taxonProfile.taxonNuid,
  };
}
