/**
 * This file describes a generated template_contents/<uuid>.json file that is generated by an app-kit build server
 *
 * todo: unknown types
 */

export type FrontendUserContentImage = {
  '1x': string
  '2x': string
  '4x': string
  '8x': string
}

export type FactSheetContent = {
  key: string
  type: 'image' | 'multi-image' | 'text'
  format?: 'layoutable-full' | 'layoutable-simple'
  widget?: 'TextInput' | 'TextArea'
  label: string
}

export type FactSheetContentWithValue = FactSheetContent & {
  value?: string | FrontendUserContentImage[] | FrontendUserContentImage
}

export type TemplateContent = {
  title: string
  slug: string
  contents: Record<string, FactSheetContentWithValue>
}

export type FactSheetTemplate = TemplateContent & {
  version: number
  templateFileName: string
  templateName: string
  templateUrl: string
  contents: Record<string, FactSheetContent>
}
