/**
 * This file describes a generated template_contents/<uuid>.json file that is generated by an app-kit build server
 */

import { ImageUrls, ImageLicence } from "../types/Image";

export type TemplateContent = {
  title: string
  slug: string
  contents: Record<string, any>
}

export enum ComponentTypes {
  image = 'image',
  text = 'text',
  templateContentLink = 'templateContentLink',
}

export enum TemplateType {
  page = 'page',
  feature = 'feature',
}

export type ComponentContent = {
  type: ComponentTypes
  required?: boolean
  helpText?: string
}

export type TemplateContentComponent = {
  templateName: string
  type: string
  version: number
  idnetifierContent: string
  contents: Record<string, ComponentContent>
}

export type Page = TemplateContent & {
  version: number
  templateFileName: string
  templateName: string
  templateUrl: string
  contents: Record<string, any>
}

export type TemplateContentNavigationEntry = {
  url: string
  children: TemplateContentNavigationEntry[]
  linkName: string
  link_name: string /** should be deprecated in the future */
}

export type TemplateContentNavigation = TemplateContentNavigationEntry[]; 

export type LicencedTemplateContentImage = {
  image : {
    imageUrl: ImageUrls | null,
    licence: ImageLicence | {}
  }
}