/**
 * This file describes a settings.json file that is generated by an app-kit build server
 */
import type { TemplateType } from "../features/TemplateContent"

type FrontendAdditionalSettings = {
  [setting: string]: string
}

type AppOptions = {
  allowAnonymousObservations: boolean,
  doNotBuildLargeImages: boolean,
}

type UserContentItem = {
  helpText: string
  required: boolean
}

export type UserContentImage = UserContentItem & {
  restrictions?: {
    fileType?: string[]
    ratio?: string
  },
}

export type UserContentText = UserContentItem
export type UserContentConfiguration = UserContentItem

type UserContent = {
  images: Record<string, UserContentImage>
  texts: Record<string, UserContentText>
  configuration: Record<string, UserContentConfiguration>
}

type TemplateContentNavigationDefinition = {
  name: string
  maxLevels: number
}

type TemplateContentDefinition = {
  templateType: TemplateType
  allowedTemplates: string[]
}

type TemplateContent = {
  urlPattern: string
  navigations?: Record<string, TemplateContentNavigationDefinition>
  requiredOfflineContents?: Record<string, TemplateContentDefinition>
}

type CordovaOptions = {
  platforms: Record<'android' | 'ios' | 'browser', string>
  plugins: string[]
}

type FrontendBaseSettings = {
  frontend: string
  version: string
  APP_UUID: string
  APP_VERSION: number
  API_URL: string
  MEDIA_URL: string
  LANGUAGES: string[]
  PRIMARY_LANGUAGE: string
  PREVIEW: boolean
  OPTIONS: AppOptions
  userContent?: UserContent
  templateContent?: TemplateContent
  cordova?: CordovaOptions
}

export type FrontendSettings = FrontendBaseSettings & FrontendAdditionalSettings
