/**
 * This file describes a generated BackboneTaxonomy/<uuid>/vernacular/<locale>.json file that is generated by an app-kit build server
 */
import {SearchableTaxonReference} from "./TaxonProfile";

export type BackboneTaxonomy = SearchableTaxonReference[];