/**
 * This file describes a generated features.json file that is generated by an app-kit build server
 */
export type FeatureType = 'Frontend' | 'BackboneTaxonomy' | 'TaxonProfiles' | 'NatureGuide' | 'GenericForm'

export type FeatureReference = {
  model: FeatureType
  uuid: string
  action: string // todo: type unknown
}

export type Feature = {
  genericContentType: FeatureType
  uuid: string
  name: string
  version: number
  path: string
  folder: string
  slug: string
}

export type DetailFeature = {
  uuid: string,
  version: number
  options: Record<string, any>,
  globalOptions: Record<string, any>
  name: string,
  slug: string
}

export type ListFeature = {
  list: Feature[],
  lookup: Record<string, string>
}

export type NatureGuideFeature = Feature & {
  startNodeSlug: string
  imageUrl: string
}

export type TemplateContentFeature = ListFeature & {
  assignments: {
    string: Record<string,string>
  },
  navigations: Record<string, any>
}

export type GlossaryFeature = Feature & {
  localized: any,
}

export type TaxonProfilesFeature = Feature & {
  search: any,
  registry: any,
}

export type Features = {
  slugs: Record<string, string>,
  Frontend: Feature,
  Glossary?: GlossaryFeature,
  BackboneTaxonomy: Feature,
  NatureGuide?: ListFeature,
  GenericForm?: ListFeature,
  TaxonProfiles: TaxonProfilesFeature,
  TemplateContent?: TemplateContentFeature,
}
